name: Main Test
on:
  push:
    branches:
      - main

jobs:
  lint_and_test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Lint Code
        run: yarn lint

      - name: Build
        run: yarn build
